module.exports = {
   jwtsecret: "DeezNuts69",
   defaultDeck: {
      decktype: "Goat Control",
      visibility: "private",
      wins: 0,
      losses: 0,
      maindeck: [
         { count: 1, name: "Black Luster Soldier - Envoy of the Beginning" },
         { count: 2, name: "Airknight Parshath" },
         { count: 2, name: "Magician of Faith" },
         { count: 2, name: "Magical Merchant" },
         { count: 2, name: "Abyss Soldier" },
         { count: 1, name: "Breaker the Magical Warrior" },
         { count: 2, name: "Tsukuyomi" },
         { count: 1, name: "Sangan" },
         { count: 1, name: "Sinister Serpent" },
         { count: 1, name: "Tribe-Infecting Virus" },
         { count: 1, name: "Morphing Jar" },
         { count: 1, name: "Pot of Greed" },
         { count: 1, name: "Graceful Charity" },
         { count: 1, name: "Delinquent Duo" },
         { count: 1, name: "Heavy Storm" },
         { count: 1, name: "Mystical Space Typhoon" },
         { count: 1, name: "Snatch Steal" },
         { count: 1, name: "Premature Burial" },
         { count: 3, name: "Metamorphosis" },
         { count: 2, name: "Scapegoat" },
         { count: 2, name: "Book of Moon" },
         { count: 2, name: "Nobleman of Crossout" },
         { count: 1, name: "Mirror Force" },
         { count: 1, name: "Torrential Tribute" },
         { count: 1, name: "Ring of Destruction" },
         { count: 1, name: "Call of the Haunted" },
         { count: 2, name: "Sakuretsu Armor" },
         { count: 2, name: "Dust Tornado" }
      ],
      sidedeck: []
   }
};
