module.exports = {
   jwtsecret: "DeezNuts69",
   defaultDeck: {
      decktype: "Goat Control",
      visibility: "private",
      wins: 0,
      losses: 0,
      maindeck: {
         "Black Luster Soldier - Envoy of the Beginning": 1,
         "Airknight Parshath": 2,
         "Magician of Faith": 2,
         "Magical Merchant": 2,
         "Abyss Soldier": 2,
         "Breaker the Magical Warrior": 1,
         Tsukuyomi: 2,
         Sangan: 1,
         "Sinister Serpent": 1,
         "Tribe-Infecting Virus": 1,
         "Morphing Jar": 1,
         "Pot of Greed": 1,
         "Graceful Charity": 1,
         "Delinquent Duo": 1,
         "Heavy Storm": 1,
         "Mystical Space Typhoon": 1,
         "Snatch Steal": 1,
         "Premature Burial": 1,
         Metamorphosis: 3,
         Scapegoat: 2,
         "Book of Moon": 2,
         "Nobleman of Crossout": 2,
         "Mirror Force": 1,
         "Torrential Tribute": 1,
         "Ring of Destruction": 1,
         "Call of the Haunted": 1,
         "Sakuretsu Armor": 2,
         "Dust Tornado": 2
      },
      sidedeck: []
   }
};
