module.exports = {
   aws_table_name: "users",
   aws_remote_config: {
      accessKeyId: "AKIAYJS555CFSKED66VX",
      secretAccessKey: "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",
      region: "us-east-2"
   },
   jwtsecret: "DeezNuts69",
   defaultDeck: {
      decktype: "Goat Control",
      default: true,
      visibility: "private",
      wins: 0,
      losses: 0,
      maindeck: [
         "Black Luster Soldier - Envoy of the Beginning",
         "Airknight Parshath",
         "Airknight Parshath",
         "Magician of Faith",
         "Magician of Faith",
         "Magical Merchant",
         "Magical Merchant",
         "Abyss Soldier",
         "Abyss Soldier",
         "Breaker the Magical Warrior",
         "Tsukuyomi",
         "Tsukuyomi",
         "Sangan",
         "Sinister Serpent",
         "Tribe-Infecting Virus",
         "Morphing Jar",
         "Pot of Greed",
         "Graceful Charity",
         "Delinquent Duo",
         "Heavy Storm",
         "Mystical Space Typhoon",
         "Snatch Steal",
         "Premature Burial",
         "Metamorphosis",
         "Metamorphosis",
         "Metamorphosis",
         "Scapegoat",
         "Scapegoat",
         "Book of Moon",
         "Book of Moon",
         "Nobleman of Crossout",
         "Nobleman of Crossout",
         "Mirror Force",
         "Torrential Tribute",
         "Ring of Destruction",
         "Call of the Haunted",
         "Sakuretsu Armor",
         "Sakuretsu Armor",
         "Dust Tornado",
         "Dust Tornado"
      ],
      sidedeck: []
   }
};
